package main

// ct converts a skill's CT (how long the user waits before acting again,
// in the same 0-100 units the ATB gauge fills at atbBaseSpeed per second)
// into the ReturnPosition the user's timeline icon reappears at.
func ct(v float64) float64 {
	return atbMax - v
}

// Player1Skills is player_1's (男1) skill set.
var Player1Skills = []SkillDef{
	{
		Name:        "スマッシュ",
		UnlockLevel: 1,
		Levels: []SkillLevelData{
			{
				Description:    "敵に中ダメージのパンチをします",
				Target:         TargetSingle,
				Element:        ElemPhysicalNone,
				PowerSingle:    150,
				MPCost:         6,
				ReturnPosition: ct(40),
				GaugePoint:     2,
			},
			{
				Description:    "敵に大ダメージのパンチをしてノックバックさせます",
				Target:         TargetSingle,
				Element:        ElemPhysicalNone,
				PowerSingle:    200,
				MPCost:         12,
				ReturnPosition: ct(55),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{PhysAtk: 20},
				Knockback:      15,
				KnockbackPerTG: 5,
			},
			{
				Description:    "敵に極大ダメージのパンチをしてノックバックさせます",
				Target:         TargetSingle,
				Element:        ElemPhysicalNone,
				PowerSingle:    280,
				MPCost:         20,
				ReturnPosition: ct(55),
				GaugePoint:     3,
				UpgradeSP:      300,
				StatBonus:      PlayerStats{PhysAtk: 40},
				Knockback:      30,
				KnockbackPerTG: 5,
			},
		},
	},
	{
		Name:        "みやぶる",
		UnlockLevel: 1,
		Levels: []SkillLevelData{
			{
				Description:    "敵単体のHPと弱点属性を調べます",
				Target:         TargetSingle,
				Element:        ElemMagicNone,
				MPCost:         5,
				ReturnPosition: ct(20),
				GaugePoint:     3,
				Scan:           true,
			},
			{
				Description:    "敵全体のHPと弱点属性を調べます",
				Target:         TargetAll,
				Element:        ElemMagicNone,
				MPCost:         8,
				ReturnPosition: ct(20),
				GaugePoint:     3,
				UpgradeSP:      50,
				StatBonus:      PlayerStats{Spd: 10, MagicAtk: 20},
				Scan:           true,
			},
			{
				Description:    "敵全体を調べた後、小ダメージの攻撃を与えます（倒せない）",
				Target:         TargetAll,
				Element:        ElemPhysicalNone,
				PowerAll:       100,
				MPCost:         15,
				ReturnPosition: ct(10),
				GaugePoint:     4,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{Spd: 20, MagicAtk: 30},
				Scan:           true,
				NonLethal:      true,
			},
		},
	},
	{
		Name:        "フレイム",
		UnlockLevel: 3,
		Levels: []SkillLevelData{
			{
				Description:    "中ダメージの炎を与えます",
				Target:         TargetBoth,
				Element:        ElemFire,
				PowerSingle:    170,
				PowerAll:       120,
				MPCost:         11,
				ReturnPosition: ct(50),
				GaugePoint:     2,
			},
			{
				Description: "大ダメージの炎を与え、魔防を小ダウンさせます",
				Target:      TargetBoth,
				Element:     ElemFire,
				PowerSingle: 230,
				PowerAll:    160,
				MPCost:      17,
				Effects: []SkillEffect{
					{Type: EffectDebuffMagicDef, Percent: 10, PercentAll: 5, Seconds: 10},
				},
				ReturnPosition: ct(65),
				GaugePoint:     2,
				UpgradeSP:      110,
				StatBonus:      PlayerStats{MagicAtk: 10, MagicDef: 10},
			},
			{
				Description: "極大ダメージの炎を与え、魔防を中ダウンさせます",
				Target:      TargetBoth,
				Element:     ElemFire,
				PowerSingle: 270,
				PowerAll:    200,
				MPCost:      32,
				Effects: []SkillEffect{
					{Type: EffectDebuffMagicDef, Percent: 15, PercentAll: 10, Seconds: 15},
				},
				ReturnPosition: ct(80),
				GaugePoint:     3,
				UpgradeSP:      320,
				StatBonus:      PlayerStats{MagicAtk: 20, MagicDef: 20},
			},
		},
	},
	{
		Name:        "回復",
		UnlockLevel: 3,
		Levels: []SkillLevelData{
			{
				Description:    "味方のHPを小回復します",
				Target:         TargetBoth,
				Element:        ElemMagicNone,
				PowerSingle:    20,
				PowerAll:       10,
				MPCost:         8,
				IsHeal:         true,
				ReturnPosition: ct(50),
				GaugePoint:     2,
			},
			{
				Description:    "味方のHPを中回復します",
				Target:         TargetBoth,
				Element:        ElemMagicNone,
				PowerSingle:    30,
				PowerAll:       15,
				MPCost:         18,
				IsHeal:         true,
				ReturnPosition: ct(60),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{HP: 30},
			},
			{
				Description:    "味方のHPを大回復し、TGレベル4以上ならMPも小回復します",
				Target:         TargetBoth,
				Element:        ElemMagicNone,
				PowerSingle:    50,
				PowerAll:       30,
				MPCost:         23,
				IsHeal:         true,
				ReturnPosition: ct(70),
				GaugePoint:     4,
				UpgradeSP:      350,
				StatBonus:      PlayerStats{HP: 50},
				TGMPHealLevel:  4,
				MPHealSingle:   10,
				MPHealAll:      5,
			},
		},
	},
	{
		Name:        "クラッシュサークル",
		UnlockLevel: 6,
		Levels: []SkillLevelData{
			{
				Description:    "魔法の力で小ダメージの広範囲攻撃",
				Target:         TargetAll,
				Element:        ElemMagicNone,
				PowerAll:       100,
				MPCost:         9,
				ReturnPosition: ct(45),
				GaugePoint:     2,
			},
			{
				Description:    "魔法の力で中ダメージの広範囲攻撃",
				Target:         TargetAll,
				Element:        ElemMagicNone,
				PowerAll:       130,
				MPCost:         15,
				ReturnPosition: ct(50),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{MagicAtk: 20},
			},
			{
				Description:    "魔法の力で大ダメージの広範囲攻撃。TGレベル3以上で威力アップ",
				Target:         TargetAll,
				Element:        ElemMagicNone,
				PowerAll:       250,
				MPCost:         35,
				ReturnPosition: ct(90),
				GaugePoint:     2,
				UpgradeSP:      300,
				StatBonus:      PlayerStats{MagicAtk: 40},
				TGPowerLevel:   3,
				TGPowerAll:     280,
			},
		},
	},
	{
		Name:        "バフ",
		UnlockLevel: 13,
		Levels: []SkillLevelData{
			{
				Description: "味方1人の物攻を小アップ",
				Target:      TargetSingle,
				Ally:        true,
				MPCost:      5,
				Effects: []SkillEffect{
					{Type: EffectBuffPhysAtkUp, Percent: 20, Seconds: 20},
				},
				ReturnPosition: ct(30),
				GaugePoint:     2,
			},
			{
				Description: "味方1人の物魔攻を中アップ",
				Target:      TargetSingle,
				Ally:        true,
				MPCost:      16,
				Effects: []SkillEffect{
					{Type: EffectBuffAtkUp, Percent: 35, Seconds: 20},
				},
				ReturnPosition: ct(50),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{PhysAtk: 20},
			},
			{
				Description: "味方1人の物魔攻を大アップ",
				Target:      TargetSingle,
				Ally:        true,
				MPCost:      23,
				Effects: []SkillEffect{
					{Type: EffectBuffAtkUp, Percent: 50, Seconds: 30},
				},
				ReturnPosition: ct(60),
				GaugePoint:     2,
				UpgradeSP:      250,
				StatBonus:      PlayerStats{PhysAtk: 20},
			},
		},
	},
}

// Player2Skills is player_2's (白髪女) skill set.
var Player2Skills = []SkillDef{
	{
		Name:        "スーパーヒーリング",
		UnlockLevel: 1,
		Levels: []SkillLevelData{
			{
				Description:    "味方のHPを回復します",
				Target:         TargetBoth,
				Element:        ElemMagicNone,
				PowerSingle:    30,
				PowerAll:       15,
				MPCost:         7,
				IsHeal:         true,
				ReturnPosition: ct(40),
				GaugePoint:     2,
			},
			{
				Description:    "味方のHPを大きく回復します",
				Target:         TargetBoth,
				Element:        ElemMagicNone,
				PowerSingle:    40,
				PowerAll:       20,
				MPCost:         16,
				IsHeal:         true,
				ReturnPosition: ct(50),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{HP: 10, PhysDef: 10},
			},
			{
				Description:    "味方のHPをとても大きく回復します",
				Target:         TargetBoth,
				Element:        ElemMagicNone,
				PowerSingle:    60,
				PowerAll:       35,
				MPCost:         27,
				IsHeal:         true,
				ReturnPosition: ct(60),
				GaugePoint:     3,
				UpgradeSP:      300,
				StatBonus:      PlayerStats{HP: 20, MagicDef: 20},
			},
		},
	},
	{
		Name:        "妖艶の舞",
		UnlockLevel: 1,
		Levels: []SkillLevelData{
			{
				Description: "味方1人の物魔攻を小アップ",
				Target:      TargetSingle,
				Ally:        true,
				MPCost:      8,
				Effects: []SkillEffect{
					{Type: EffectBuffAtkUp, Percent: 10, Seconds: 30},
				},
				ReturnPosition: ct(60),
				GaugePoint:     2,
			},
			{
				Description: "味方1人の物魔攻を中アップ",
				Target:      TargetSingle,
				Ally:        true,
				MPCost:      19,
				Effects: []SkillEffect{
					{Type: EffectBuffAtkUp, Percent: 30, Seconds: 30},
				},
				ReturnPosition: ct(65),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{PhysAtk: 20},
			},
			{
				Description: "味方全員の物魔攻を大アップ",
				Target:      TargetAll,
				Ally:        true,
				MPCost:      30,
				Effects: []SkillEffect{
					{Type: EffectBuffAtkUp, Percent: 50, PercentAll: 50, Seconds: 30},
				},
				ReturnPosition: ct(70),
				GaugePoint:     3,
				UpgradeSP:      290,
				StatBonus:      PlayerStats{PhysAtk: 40},
			},
		},
	},
	{
		Name:        "フィナーレソング",
		UnlockLevel: 7,
		Levels: []SkillLevelData{
			{
				Description: "敵全体に魔法ダメージを与え、物魔防を小ダウン",
				Target:      TargetAll,
				Element:     ElemMagicNone,
				PowerAll:    130,
				MPCost:      10,
				Effects: []SkillEffect{
					{Type: EffectDebuffDefBoth, Percent: 10, PercentAll: 10, Seconds: 30},
				},
				ReturnPosition: ct(70),
				GaugePoint:     2,
			},
			{
				Description: "敵全体に魔法ダメージを与え、物魔防を中ダウン",
				Target:      TargetAll,
				Element:     ElemMagicNone,
				PowerAll:    170,
				MPCost:      20,
				Effects: []SkillEffect{
					{Type: EffectDebuffDefBoth, Percent: 30, PercentAll: 30, Seconds: 30},
				},
				ReturnPosition: ct(80),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{MagicAtk: 10, Spd: 5},
			},
			{
				Description: "敵全体に魔法ダメージを与え、物魔防を大ダウン",
				Target:      TargetAll,
				Element:     ElemMagicNone,
				PowerAll:    200,
				MPCost:      30,
				Effects: []SkillEffect{
					{Type: EffectDebuffDefBoth, Percent: 50, PercentAll: 50, Seconds: 30},
				},
				ReturnPosition: ct(90),
				GaugePoint:     3,
				UpgradeSP:      330,
				StatBonus:      PlayerStats{MagicAtk: 20, Spd: 10},
			},
		},
	},
	{
		Name:        "氷のつぶて",
		UnlockLevel: 10,
		Levels: []SkillLevelData{
			{
				Description:    "氷のつぶてで中ダメージを与えます",
				Target:         TargetBoth,
				Element:        ElemIce,
				PowerSingle:    150,
				PowerAll:       100,
				MPCost:         6,
				ReturnPosition: ct(50),
				GaugePoint:     2,
			},
			{
				Description:    "氷のつぶてで大ダメージを与えます",
				Target:         TargetBoth,
				Element:        ElemIce,
				PowerSingle:    180,
				PowerAll:       130,
				MPCost:         16,
				ReturnPosition: ct(60),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{MagicAtk: 20},
			},
			{
				Description:    "氷のつぶてで極大ダメージを与えます",
				Target:         TargetBoth,
				Element:        ElemIce,
				PowerSingle:    210,
				PowerAll:       160,
				MPCost:         22,
				ReturnPosition: ct(70),
				GaugePoint:     2,
				UpgradeSP:      300,
				StatBonus:      PlayerStats{MagicAtk: 40},
			},
		},
	},
	{
		Name:        "聖なる魔法",
		UnlockLevel: 14,
		Levels: []SkillLevelData{
			{
				Description:    "聖なる光で敵全体に中ダメージを与えます",
				Target:         TargetAll,
				Element:        ElemMagicNone,
				PowerAll:       130,
				MPCost:         10,
				ReturnPosition: ct(70),
				GaugePoint:     4,
			},
			{
				Description:    "聖なる光で敵全体に大ダメージを与えます",
				Target:         TargetAll,
				Element:        ElemMagicNone,
				PowerAll:       170,
				MPCost:         20,
				ReturnPosition: ct(80),
				GaugePoint:     4,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{MagicAtk: 10, Spd: 5},
			},
			{
				Description:    "聖なる光で敵全体に極大ダメージを与えます",
				Target:         TargetAll,
				Element:        ElemMagicNone,
				PowerAll:       200,
				MPCost:         30,
				ReturnPosition: ct(90),
				GaugePoint:     5,
				UpgradeSP:      330,
				StatBonus:      PlayerStats{MagicAtk: 20, Spd: 10},
			},
		},
	},
	{
		Name:        "レイズ",
		UnlockLevel: 25,
		Levels: []SkillLevelData{
			{
				Description:     "戦闘不能の味方1人をHP20%で復活させます",
				Target:          TargetSingle,
				MPCost:          18,
				ReviveHPPercent: 20,
				ReturnPosition:  ct(90),
				GaugePoint:      2,
			},
			{
				Description:     "戦闘不能の味方1人をHP50%で復活させます",
				Target:          TargetSingle,
				MPCost:          29,
				ReviveHPPercent: 50,
				ReturnPosition:  ct(70),
				GaugePoint:      2,
				UpgradeSP:       100,
				StatBonus:       PlayerStats{HP: 10, MagicDef: 10},
			},
			{
				Description:     "戦闘不能の味方全員をHP30%で復活させます",
				Target:          TargetAll,
				MPCost:          36,
				ReviveHPPercent: 30,
				ReturnPosition:  ct(50),
				GaugePoint:      3,
				UpgradeSP:       320,
				StatBonus:       PlayerStats{HP: 20, PhysDef: 20},
			},
		},
	},
}

// Player3Skills is player_3's (男2) skill set.
var Player3Skills = []SkillDef{
	{
		Name:        "かばう",
		UnlockLevel: 1,
		Levels: []SkillLevelData{
			{
				Description:    "敵の単体攻撃を3回代わりに受けます",
				Target:         TargetSelf,
				MPCost:         6,
				CoverCount:     3,
				ReturnPosition: ct(20),
				GaugePoint:     2,
			},
			{
				Description: "敵の単体攻撃を3回代わりに受けながら物防を中アップします",
				Target:      TargetSelf,
				MPCost:      18,
				CoverCount:  3,
				Effects: []SkillEffect{
					{Type: EffectBuffPhysDefUp, Percent: 20},
				},
				ReturnPosition: ct(40),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{PhysDef: 20},
			},
			{
				Description: "敵の単体攻撃を4回代わりに受けながら物魔防を大アップします",
				Target:      TargetSelf,
				MPCost:      30,
				CoverCount:  4,
				Effects: []SkillEffect{
					{Type: EffectBuffDefBothUp, Percent: 50},
				},
				ReturnPosition: ct(70),
				GaugePoint:     2,
				UpgradeSP:      300,
				StatBonus:      PlayerStats{HP: 30, Spd: 10},
			},
		},
	},
	{
		Name:        "ねこキック",
		UnlockLevel: 1,
		Levels: []SkillLevelData{
			{
				Description:    "中ダメージのキック。物防が下がった敵には確定クリティカル",
				Target:         TargetSingle,
				Element:        ElemPhysicalNone,
				PowerSingle:    130,
				MPCost:         9,
				ReturnPosition: ct(40),
				GaugePoint:     2,
				CritVsDefDown:  true,
			},
			{
				Description:    "大ダメージのキック。物防が下がった敵には確定クリティカル",
				Target:         TargetSingle,
				Element:        ElemPhysicalNone,
				PowerSingle:    180,
				MPCost:         17,
				ReturnPosition: ct(55),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{PhysAtk: 20},
				CritVsDefDown:  true,
			},
			{
				Description:    "極大ダメージのキック。物防が下がった敵には確定クリティカル",
				Target:         TargetSingle,
				Element:        ElemPhysicalNone,
				PowerSingle:    250,
				MPCost:         27,
				ReturnPosition: ct(55),
				GaugePoint:     3,
				UpgradeSP:      300,
				StatBonus:      PlayerStats{PhysAtk: 40},
				CritVsDefDown:  true,
			},
		},
	},
	{
		Name:        "エレクトロパンチ",
		UnlockLevel: 5,
		Levels: []SkillLevelData{
			{
				Description:    "敵単体に中ダメージの雷のパンチをします",
				Target:         TargetSingle,
				Element:        ElemLightning,
				Physical:       true,
				PowerSingle:    180,
				MPCost:         11,
				ReturnPosition: ct(50),
				GaugePoint:     2,
			},
			{
				Description:    "敵単体に大ダメージの雷のパンチをします",
				Target:         TargetSingle,
				Element:        ElemLightning,
				Physical:       true,
				PowerSingle:    250,
				MPCost:         17,
				ReturnPosition: ct(65),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{PhysAtk: 20},
			},
			{
				Description:    "敵単体に極大ダメージの雷のパンチをします",
				Target:         TargetSingle,
				Element:        ElemLightning,
				Physical:       true,
				PowerSingle:    300,
				MPCost:         32,
				ReturnPosition: ct(80),
				GaugePoint:     3,
				UpgradeSP:      320,
				StatBonus:      PlayerStats{PhysAtk: 40},
			},
		},
	},
	{
		Name:        "防御バフ",
		UnlockLevel: 10,
		Levels: []SkillLevelData{
			{
				Description: "味方1人の物防を小アップ",
				Target:      TargetSingle,
				Ally:        true,
				MPCost:      5,
				Effects: []SkillEffect{
					{Type: EffectBuffPhysDefUp, Percent: 20, Seconds: 20},
				},
				ReturnPosition: ct(30),
				GaugePoint:     2,
			},
			{
				Description: "味方1人の物魔防を中アップ",
				Target:      TargetSingle,
				Ally:        true,
				MPCost:      16,
				Effects: []SkillEffect{
					{Type: EffectBuffDefBothUp, Percent: 35, Seconds: 20},
				},
				ReturnPosition: ct(50),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{PhysDef: 20},
			},
			{
				Description: "味方1人の物魔防を大アップ",
				Target:      TargetSingle,
				Ally:        true,
				MPCost:      23,
				Effects: []SkillEffect{
					{Type: EffectBuffDefBothUp, Percent: 50, Seconds: 30},
				},
				ReturnPosition: ct(60),
				GaugePoint:     2,
				UpgradeSP:      250,
				StatBonus:      PlayerStats{PhysDef: 20, MagicDef: 20},
			},
		},
	},
	{
		Name:        "カウンター",
		UnlockLevel: 15,
		Levels: []SkillLevelData{
			{
				Description:    "攻撃してきた敵に反撃するカウンター状態になります",
				Target:         TargetSelf,
				MPCost:         10,
				CounterSeconds: 20,
				ReturnPosition: ct(40),
				GaugePoint:     2,
			},
			{
				Description:    "威力アップしたカウンター状態になります",
				Target:         TargetSelf,
				MPCost:         20,
				CounterSeconds: 20,
				CounterBonus:   25,
				ReturnPosition: ct(50),
				GaugePoint:     2,
				UpgradeSP:      100,
			},
			{
				Description:    "さらに威力アップしたカウンター状態になります",
				Target:         TargetSelf,
				MPCost:         32,
				CounterSeconds: 30,
				CounterBonus:   50,
				ReturnPosition: ct(60),
				GaugePoint:     3,
				UpgradeSP:      360,
			},
		},
	},
	{
		Name:        "守りの祈り",
		UnlockLevel: 25,
		Levels: []SkillLevelData{
			{
				Description:    "HPが10%以下になる攻撃を1回だけ無効にします",
				Target:         TargetSingle,
				Ally:           true,
				MPCost:         12,
				GuardHPPercent: 10,
				GuardCount:     1,
				ReturnPosition: ct(60),
				GaugePoint:     2,
			},
			{
				Description:    "HPが19%以下になる攻撃を1回だけ無効にします",
				Target:         TargetSingle,
				Ally:           true,
				MPCost:         20,
				GuardHPPercent: 19,
				GuardCount:     1,
				ReturnPosition: ct(80),
				GaugePoint:     2,
				UpgradeSP:      100,
			},
			{
				Description:    "HPが25%以下になる攻撃を2回まで無効にします",
				Target:         TargetSingle,
				Ally:           true,
				MPCost:         30,
				GuardHPPercent: 25,
				GuardCount:     2,
				ReturnPosition: ct(90),
				GaugePoint:     3,
				UpgradeSP:      350,
			},
		},
	},
}

// axeDebuffSeconds is how long the Lv.3 elemental axes' debuffs last (the
// design table leaves it unspecified).
const axeDebuffSeconds = 20

// Player4Skills is player_4's (紫女) skill set.
var Player4Skills = []SkillDef{
	{
		Name:        "フレイムアックス",
		UnlockLevel: 1,
		Levels: []SkillLevelData{
			{
				Description:    "炎の斧で大ダメージの攻撃",
				Target:         TargetSingle,
				Element:        ElemFire,
				Physical:       true,
				PowerSingle:    200,
				MPCost:         15,
				ReturnPosition: ct(50),
				GaugePoint:     3,
			},
			{
				Description:    "炎の斧で極大ダメージの攻撃",
				Target:         TargetSingle,
				Element:        ElemFire,
				Physical:       true,
				PowerSingle:    250,
				MPCost:         26,
				ReturnPosition: ct(60),
				GaugePoint:     3,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{PhysAtk: 20},
			},
			{
				Description: "炎の斧で超極大ダメージの攻撃を与え、対象の物防をダウン",
				Target:      TargetSingle,
				Element:     ElemFire,
				Physical:    true,
				PowerSingle: 320,
				MPCost:      34,
				Effects: []SkillEffect{
					{Type: EffectDebuffPhysicalDef, Percent: 15, Seconds: axeDebuffSeconds},
				},
				ReturnPosition: ct(80),
				GaugePoint:     5,
				UpgradeSP:      360,
				StatBonus:      PlayerStats{PhysAtk: 40},
			},
		},
	},
	{
		Name:        "ドレインアックス",
		UnlockLevel: 1,
		Levels: []SkillLevelData{
			{
				Description:    "攻撃時、そのダメージに応じてMPも回復します（最大10）",
				Target:         TargetSingle,
				Element:        ElemPhysicalNone,
				PowerSingle:    120,
				MPCost:         7,
				ReturnPosition: ct(30),
				GaugePoint:     2,
				DrainDivisor:   20,
				DrainMax:       10,
			},
			{
				Description:    "攻撃時、そのダメージに応じてMPも回復します（最大20）",
				Target:         TargetSingle,
				Element:        ElemPhysicalNone,
				PowerSingle:    170,
				MPCost:         14,
				ReturnPosition: ct(40),
				GaugePoint:     2,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{PhysAtk: 20},
				DrainDivisor:   20,
				DrainMax:       20,
			},
			{
				Description:    "攻撃時、そのダメージに応じてMPも回復します（最大30）",
				Target:         TargetSingle,
				Element:        ElemPhysicalNone,
				PowerSingle:    230,
				MPCost:         19,
				ReturnPosition: ct(45),
				GaugePoint:     3,
				UpgradeSP:      300,
				StatBonus:      PlayerStats{PhysAtk: 40},
				DrainDivisor:   20,
				DrainMax:       30,
			},
		},
	},
	{
		Name:        "ヒャッコルアックス",
		UnlockLevel: 3,
		Levels: []SkillLevelData{
			{
				Description:    "氷の斧で大ダメージの攻撃",
				Target:         TargetSingle,
				Element:        ElemIce,
				Physical:       true,
				PowerSingle:    200,
				MPCost:         18,
				ReturnPosition: ct(50),
				GaugePoint:     3,
			},
			{
				Description:    "氷の斧で極大ダメージの攻撃",
				Target:         TargetSingle,
				Element:        ElemIce,
				Physical:       true,
				PowerSingle:    250,
				MPCost:         26,
				ReturnPosition: ct(60),
				GaugePoint:     3,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{PhysAtk: 20},
			},
			{
				Description: "氷の斧で超極大ダメージの攻撃を与え、対象の物攻をダウン",
				Target:      TargetSingle,
				Element:     ElemIce,
				Physical:    true,
				PowerSingle: 320,
				MPCost:      34,
				Effects: []SkillEffect{
					{Type: EffectDebuffPhysAtk, Percent: 15, Seconds: axeDebuffSeconds},
				},
				ReturnPosition: ct(80),
				GaugePoint:     5,
				UpgradeSP:      360,
				StatBonus:      PlayerStats{PhysAtk: 40},
			},
		},
	},
	{
		Name:        "エレクトロアックス",
		UnlockLevel: 10,
		Levels: []SkillLevelData{
			{
				Description:    "雷の斧で大ダメージの攻撃",
				Target:         TargetSingle,
				Element:        ElemLightning,
				PowerSingle:    200,
				MPCost:         15,
				ReturnPosition: ct(50),
				GaugePoint:     3,
			},
			{
				Description:    "雷の斧で極大ダメージの攻撃",
				Target:         TargetSingle,
				Element:        ElemLightning,
				PowerSingle:    250,
				MPCost:         26,
				ReturnPosition: ct(60),
				GaugePoint:     3,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{MagicAtk: 20},
			},
			{
				Description: "雷の斧で超極大ダメージの攻撃を与え、対象の魔防をダウン",
				Target:      TargetSingle,
				Element:     ElemLightning,
				PowerSingle: 320,
				MPCost:      34,
				Effects: []SkillEffect{
					{Type: EffectDebuffMagicDef, Percent: 15, Seconds: axeDebuffSeconds},
				},
				ReturnPosition: ct(80),
				GaugePoint:     5,
				UpgradeSP:      360,
				StatBonus:      PlayerStats{MagicAtk: 40},
			},
		},
	},
	{
		Name:        "ウィンガアックス",
		UnlockLevel: 15,
		Levels: []SkillLevelData{
			{
				Description:    "風の斧で大ダメージの攻撃",
				Target:         TargetSingle,
				Element:        ElemWind,
				PowerSingle:    200,
				MPCost:         15,
				ReturnPosition: ct(50),
				GaugePoint:     3,
			},
			{
				Description:    "風の斧で極大ダメージの攻撃",
				Target:         TargetSingle,
				Element:        ElemWind,
				PowerSingle:    250,
				MPCost:         26,
				ReturnPosition: ct(60),
				GaugePoint:     3,
				UpgradeSP:      100,
				StatBonus:      PlayerStats{MagicAtk: 20},
			},
			{
				Description: "風の斧で超極大ダメージの攻撃を与え、対象の魔攻をダウン",
				Target:      TargetSingle,
				Element:     ElemWind,
				PowerSingle: 320,
				MPCost:      34,
				Effects: []SkillEffect{
					{Type: EffectDebuffMagicAtk, Percent: 15, Seconds: axeDebuffSeconds},
				},
				ReturnPosition: ct(80),
				GaugePoint:     5,
				UpgradeSP:      360,
				StatBonus:      PlayerStats{MagicAtk: 40},
			},
		},
	},
	{
		Name:        "アックスメテオ",
		UnlockLevel: 30,
		Levels: []SkillLevelData{
			{
				Description:    "メテオを呼び出し極大ダメージの攻撃をぶつける",
				Target:         TargetAll,
				Element:        ElemMagicNone,
				PowerAll:       250,
				MPCost:         27,
				ReturnPosition: ct(80),
				GaugePoint:     4,
			},
			{
				Description:    "メテオを呼び出し超極大ダメージの攻撃をぶつける",
				Target:         TargetAll,
				Element:        ElemMagicNone,
				PowerAll:       280,
				MPCost:         42,
				ReturnPosition: ct(90),
				GaugePoint:     4,
				UpgradeSP:      150,
				StatBonus:      PlayerStats{MagicAtk: 20},
			},
			{
				Description:    "そして天は鳴き大地を震わせるアセンションの時、メテオは飛来する。",
				Target:         TargetAll,
				Element:        ElemMagicNone,
				PowerAll:       350,
				MPCost:         53,
				ReturnPosition: ct(100),
				GaugePoint:     6,
				UpgradeSP:      400,
				StatBonus:      PlayerStats{MagicAtk: 40},
				Knockback:      30,
			},
		},
	},
}
