// Command genloadingfont generates ../../loading_glyphs.go: the dot patterns
// of the characters in the "Loading..." indicator, taken from the game font.
// The indicator is drawn from these patterns instead of the font file so it
// can show the game font's look from the very first frame, before
// k8x12.ttf (1.2MB) has been downloaded. Re-run after changing the label:
//
//	go run ./tools/genloadingfont
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"image"
	"image/draw"
	"log"
	"os"
	"strings"

	"golang.org/x/image/font"
	"golang.org/x/image/font/opentype"
	"golang.org/x/image/math/fixed"
)

const (
	fontPath = "assets/fonts/k8x12.ttf"
	outPath  = "loading_glyphs.go"
	// chars must cover loadingLabel and loadingDotRune in loading_indicator.go.
	chars = "Loading."
	// fontPx is k8x12's design size: at 12px every glyph lands on whole pixels.
	fontPx = 12
)

func main() {
	data, err := os.ReadFile(fontPath)
	if err != nil {
		log.Fatal(err)
	}
	f, err := opentype.Parse(data)
	if err != nil {
		log.Fatal(err)
	}
	face, err := opentype.NewFace(f, &opentype.FaceOptions{Size: fontPx, DPI: 72, Hinting: font.HintingNone})
	if err != nil {
		log.Fatal(err)
	}
	defer face.Close()

	m := face.Metrics()
	ascent := m.Ascent.Ceil()
	height := ascent + m.Descent.Ceil()

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by go run ./tools/genloadingfont; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package main\n\n")
	fmt.Fprintf(&buf, "// loadingGlyphHeight は loadingGlyphs の各文字の高さ(ドット)。\n")
	fmt.Fprintf(&buf, "const loadingGlyphHeight = %d\n\n", height)
	fmt.Fprintf(&buf, "// loadingGlyphs は k8x12.ttf の文字のドットパターン(#が点)。\n")
	fmt.Fprintf(&buf, "var loadingGlyphs = map[rune][]string{\n")
	seen := map[rune]bool{}
	for _, r := range chars {
		if seen[r] {
			continue
		}
		seen[r] = true
		adv, ok := face.GlyphAdvance(r)
		if !ok {
			log.Fatalf("%q is not in %s", r, fontPath)
		}
		w := adv.Ceil()
		img := image.NewAlpha(image.Rect(0, 0, w, height))
		draw.Draw(img, img.Bounds(), image.Transparent, image.Point{}, draw.Src)
		d := font.Drawer{Dst: img, Src: image.White, Face: face, Dot: fixed.P(0, ascent)}
		d.DrawString(string(r))
		fmt.Fprintf(&buf, "\t%q: {\n", r)
		for y := 0; y < height; y++ {
			var row strings.Builder
			for x := 0; x < w; x++ {
				if img.AlphaAt(x, y).A >= 0x80 {
					row.WriteByte('#')
				} else {
					row.WriteByte('.')
				}
			}
			fmt.Fprintf(&buf, "\t\t%q,\n", row.String())
		}
		fmt.Fprintf(&buf, "\t},\n")
	}
	fmt.Fprintf(&buf, "}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		log.Fatal(err)
	}
}
